### ISSUE TITLE
Toolbar and Sidenav fixed in sidenav-layout

### ISSUE THREAD

**Issue by sp33dlink** [angular/material2#2033]
I'd like to have to Toolbar and the sidenav fixed in my Layout so that only the content is scrolling like the angular 2 docs site: https://angular.io/docs/ts/latest/

This must somehow be possible with the sidenav-layout as many users would like to use this behavior. But i can't get it to work like this.

Plunker: http://plnkr.co/edit/SCkBpDvvWZgGCZKhWDIp?p=preview
This plunker lacks the fixed layout of the sidenavand the scrollbar on the right should only be displayed if the content height is more than the screen height.

**Comment by michaeljota** [comment]
Rather that seeing as the Toolbar and the sidenav should be fixed in the layout, I guess that the content of the sidenav-layout must be wrapped. This would allow for the expect behavior, but with so much less effort, and must be clearer what it is the intent and why this is happening. Also, I guess you can just wrap yourself the content of the sidenav-layout as a workaround. One more thing, you may want to clear the styles and just place the toolbar inside the sidenav-layout for this to work, however, it is expected to the sidenav overlap the toolbar anyway.

**Comment by greg-md** [comment]
Just put the md-sidenav out of layout.

<md-sidenav>Fixed sidenav</md-sidenav>

<md-sidenav-layout></md-sidenav-layout>

**Comment by joerg-bergner** [comment]
+1

**Comment by RaulRG** [comment]
@greg-md I think this is not what @sp33dlink needs. I would like the same feature. Material Design Lite (MDL) calls it fixed header I think. The toolbar stays at the top of your page even if you need to scroll the content. With the current behaviour the toolbar scrolls out of sight if you need to scroll down to see the content.

**Comment by greg-md** [comment]
@RaulRG, just add style position fixed to the md-sidenav and toolbar will remain on the screen.

**Comment by RaulRG** [comment]
Thank you @greg-md , but I don't understand what you mean. This is my current layout:

`<md-toolbar><span>My Title</span></md-toolbar>`
`<md-sidenav-layout>`
`      <md-sidenav align="begin" mode="push" #sidenav>`
`      </md-sidenav>`
`</md-sidenav-layout>`

When I open the sidenav using a button (like a hamburger menu not shown in the code above), I want the sidenav to be below the toolbar and to the left. 

I tried setting the position to fixed for both the navbar and the toolbar and I don't get the desired result. When I set the position to fixed for the toolbar it disappears!!

Sorry if I didn't understand you.

**Comment by greg-md** [comment]
@RaulRG as I said in my first comment, just pull out `md-sidenav` from the `md-sidenav-layout` and set fixed position to it.

_Example:_
```html
<md-toolbar style="position:fixed;"><span>My Title</span></md-toolbar>
<md-sidenav style="position:fixed;" align="begin" mode="push" #sidenav></md-sidenav>
<md-sidenav-layout></md-sidenav-layout>
```

**Comment by PrazSam** [comment]
I'm having the same issue as @RaulRG said. Toolbar just diapered when using the way @greg-md mentioned. This issue is a real headache. Hope they will fix this soon.

**Comment by PrazSam** [comment]
@RaulRG I just fixed it following the accepted answer of this[ stackoverflow question ](http://stackoverflow.com/questions/39683548/sticky-mdtoolbar-inside-mdsidenavlayout). Have a look.

**Comment by greg-md** [comment]
@PrazSam I don't know what is not working for both of you, maybe we misunderstood each other.

Here is a example with what I'm talking about: http://plnkr.co/edit/XfQxFVH8ZgQo0SsHCKA5?p=preview

**Comment by marius-oprea** [comment]
I also have this issue.
I'm following the layout described in the documentation: https://material.angular.io/components/component/sidenav
I have the toolbar inside the md-sidenav-container, because I want the sidenav to overlay the toolbar and app-container when open. 
I also have an action button of type floating with position: fixed.

If the content of the app-container is big enough to scroll, the toolbar and the action button will scroll also.

I want to keep this layout, without moving the floating button and toolbar outside the md-sidenav-container.

```
<md-sidenav-container>
  <md-toolbar style='position: fixed;'>My App</md-toolbar>
  <md-sidenav>...</md-sidenav>
  <div id="app-container" style="height: calc(100% - 64px);">
    .....
    <button md-fab style="position: fixed;">
        <md-icon>check</md-icon>
    </button> 
  </div>
</md-sidenav-container>
```

**Comment by cuongnm265** [comment]
@PrazSam Which version are you using? I followed that answer and it still doesn't work. I'm using ^2.0.0-beta.3

**Comment by PrazSam** [comment]
@cuongnm265 It's working for ^2.0.0-beta.2 which I'm currently using. Seems there is no change in their [beta.3 release](https://github.com/angular/material2/releases) on it and should work. What I did was the exact same way the StackOverflow says.

**Comment by axtho** [comment]
I also would like to know how to get that working with a similar setup as the angular site. Currently my layout is like this:

<img width="546" alt="bildschirmfoto 2017-05-31 um 14 07 59" src="https://cloud.githubusercontent.com/assets/11181579/26631312/b5e67582-460a-11e7-804f-02f6d71f2db0.png">

The main part of the scss for the main container (where the image is from) looks rather unimpressive:

```
html, body, mh-app, md-sidenav-container {
  * {
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
  }
  main {
    min-height: 100%;
    .mat-sidenav {
      min-width: 30vw;
      .mat-button {
        width: 100%;
        position: relative;
        bottom: 0;
        margin: 24px 0;
      }
    }
    .mat-toolbar {
      box-shadow: 0 2px 1px -1px rgba(0,0,0,.2), 0 1px 1px 0 rgba(0,0,0,.14), 0 1px 3px 0 rgba(0,0,0,.12);
      z-index: 1;
      .mat-icon {
        cursor: pointer;
      }
    }
  }
}
... (there is more color and spacing styling going on below)
```

I have tried to add `overflow: hidden` to the `md-sidenav-container`, but to no success.

Isn't there a simple setup to achieve this?
Looking at Covalent's layout there seems nothing amazing going on, except for the main layout component they use, which has in it's scss the following:

```
:host {
  display: flex;
  margin: 0;
  width: 100%;
  min-height: 100%;
  height: 100%;
  overflow: hidden;

  /deep/ {
    & > md-sidenav-container > md-sidenav {
      display: -webkit-box;
      display: -webkit-flex;
      display: -moz-box;
      display: -ms-flexbox;
      display: flex;
      flex-direction: column;
    }
  }
}
```
... with the `overflow: hidden` being again the interesting part.
The above plunkers do not work anymore.

Any help or pointers would be welcome.

**Comment by tstephansen** [comment]
This may not be the "right" way to do it but I came up with a solution that works for me. 

### app.component.scss
```
.md-sidenav-isopen {
    position: absolute;
    top: 0px;
    bottom: 0px;
    left: 0px;
    right: 0px;
    padding-top: 64px;
}
    
.md-sidenav-isclosed {
    position: unset;
}
```

### app.component.html
```
<div style="width:100%;height:100%;position:absolute;top:0;bottom:0;display:flex;flex-direction:column">
    <appc-header></appc-header>
    <md-sidenav-container style="height:100%;width:100%;background-color:transparent" 
        [class.md-sidenav-isopen]="sidenavService.isOpen" 
        [class.md-sidenav-isclosed]="!sidenavService.isOpen">
        <md-sidenav mode="over" #sidenav [opened]="sidenavService.isOpen" (close)="sidenavService.close()">
            <!-- YOUR SIDENAV CONTENT HERE -->
        </md-sidenav>
        <div>
            <div style="margin-top:4em;margin-bottom:4em;">
                <router-outlet></router-outlet>
            </div>
        </div>
    </md-sidenav-container>
</div>
```

### app.component.ts
Import the SidenavService.
Add public sidenavService: SidenavService to the constructor of the component.

### sidenav.service.ts

```
import { Injectable } from '@angular/core';

@Injectable()
export class SidenavService {
  public isOpen: boolean;

  constructor() {
    this.isOpen = false;
  }

  public open() {
    this.isOpen = true;
  }

  public close() {
    this.isOpen = false;
  }
}

```

### header.component.ts
Import the SidenavService in the component.

### header.component.html

```
<md-toolbar color="primary" style="min-height:64px;">
    <span>
        <button style="background-color:transparent;border-style:none;cursor:pointer;" (click)="sidenavService.open()">
            <i class="material-icons toolbar-link-icon" style="color:white;">menu</i>
        </button>
    </span>
    <span>My Angular Material App</span>
    <span class="fill-space"></span>
</md-toolbar>
```

If you can figure out a better way to do this then let me know. I'm still learning Angular (C# / WPF developer at heart) so I'll gladly accept any criticism or pointers.

**Comment by stefanoguglielmi** [comment]
i added the following css code to fix the sidenav:

```css
.mat-sidenav-container {
    min-height: 100%;
    max-width: 100%;
    width: 100%;
    height: 100vh;
}
.mat-sidenav {
    min-width: 250px;
    position: fixed;
    top: 0;
    bottom: 0;
    left: 0;
    padding: 0;
    height: 100vh;
}

```

**Comment by nayfin** [comment]
Here's a [plunk](http://plnkr.co/edit/CLCx8BHeImj39etK4bB2?p=preview) w/fixed header, a routed body, and one of the routes has a sidenav with fixed header. Be sure to check the global css file for the tweaks that made everything work:
```
.body-content {
  overflow: auto;
}

html, body {
  height:100%;
  min-height:100vh;
  margin:0;
}
.mat-sidenav-content {
  flex: 1;
}
```
Not happy with setting `.mat-sidenav-content` globally. Please let me know if you have alternative or manage to clean anything else up.

**Comment by BamiGorengo** [comment]
@tstephansen What exactly you do? that the background is sticky when the sidenav is opend?

**Comment by mmalerba** [comment]
Sidenav now supports fixed layout, docs are coming in https://github.com/angular/material2/pull/7775
