### ISSUE TITLE
this dialog style is not work,seems no have

### ISSUE THREAD

**Issue by Striveyazi** [angular/material2#2228]
i use your demo code , but the css style is wrong, can you tell me that what are the possible causes of this error.
demo link:
https://github.com/angular/material2/blob/master/src/demo-app/dialog/dialog-demo.ts

error style:
![image](https://cloud.githubusercontent.com/assets/18276182/21208683/7dee1e84-c2aa-11e6-918c-2c737824caf5.png)
expect style:
like this 
![image](https://cloud.githubusercontent.com/assets/18276182/21208730/e064911a-c2aa-11e6-9e20-4a325b675aaa.png)
 i need your help

**Comment by crisbeto** [comment]
These are the proper dialog styles. We recently switched to using flexbox to center the dialog (see https://github.com/angular/material2/pull/1962), instead of `transform`, because using transforms can cause the dialog contents to become fuzzy in certain conditions (e.g. when the dialog's width or height isn't a whole number). Are you experiencing any rendering issues?

**Comment by Striveyazi** [comment]
thank u very much. your mean is cleaning node_modules/@angular or  node_modules/@angular/material  and reinstalling this.
i have done both . the position still is incorrect?

**Comment by Striveyazi** [comment]
angular version: 2.3.0
material verison:2.0.0-alpha.11-3

**Comment by crisbeto** [comment]
Both should do the trick. Also clearing the `node_modules` should be fine. Otherwise can you post a screenshot of what the dialog looks like for you?

**Comment by Striveyazi** [comment]
![image](https://cloud.githubusercontent.com/assets/18276182/21216497/201ab5dc-c2e2-11e6-8e75-9871051b38ce.png)

**Comment by Striveyazi** [comment]
![qq 20161215161823](https://cloud.githubusercontent.com/assets/18276182/21216525/3e95611a-c2e2-11e6-895f-f56aab084d92.png)

**Comment by Striveyazi** [comment]
i need it in center , or i can  custom  this position. my css style maybe cause  this problem? or not it's version problem?

**Comment by crisbeto** [comment]
It should be in the center by default. I'm trying it out locally and it works fine. It's hard to know what is going on just by looking at a screenshot, but the following CSS rules are what makes it work, in addition to the ones that are set as inline styles:

```css
.md-overlay-container {
  position: fixed;
  z-index: 1000;
}
.md-overlay-container, .md-global-overlay-wrapper {
  pointer-events: none;
  top: 0;
  left: 0;
  height: 100%;
  width: 100%;
}

.md-global-overlay-wrapper {
  display: flex;
  position: absolute;
  z-index: 1000;
}
```

If these aren't in your stylesheet, then it's probably outdated.

**Comment by Striveyazi** [comment]
![image](https://cloud.githubusercontent.com/assets/18276182/21216885/3a614d46-c2e4-11e6-8701-e1d875eecdcf.png)

**Comment by Striveyazi** [comment]
![image](https://cloud.githubusercontent.com/assets/18276182/21216939/85e1fa54-c2e4-11e6-9a4a-4340b48f08d1.png)

**Comment by crisbeto** [comment]
It's not supposed to be in the `element.style` (those are the inline styles), but it *should* show up right below it. It would be a good idea to try and clear out the node modules, as well as your cache and try to reinstall Material. Something similar happened here, but was fixed with a fresh install https://github.com/angular/material2/issues/2136

**Comment by Striveyazi** [comment]
I suspect that because this version of the style file is not loaded properly, you think there may be what causes it?

**Comment by Striveyazi** [comment]
I'll try what you just said

**Comment by crisbeto** [comment]
Most likely, I'm not sure what your setup is, although I can also see that some of your other CSS might be missing (e.g. the dialog backdrop is supposed to be dark, but yours looks transparent).

**Comment by Striveyazi** [comment]
i'm sorry. i did as yor said. but this problem is still exist.  my node_module/@angluar/material/dialog
/dialog-container.css it's content as follows:
/**
 * Applies styles for users in high contrast mode. Note that this only applies
 * to Microsoft browsers. Chrome can be included by checking for the `html[hc]`
 * attribute, however Chrome handles high contrast differently.
 */
md-dialog-container {
  box-shadow: 0px 11px 15px -7px rgba(0, 0, 0, 0.2), 0px 24px 38px 3px rgba(0, 0, 0, 0.14), 0px 9px 46px 8px rgba(0, 0, 0, 0.12);
  display: block;
  padding: 24px;
  border-radius: 2px;
  box-sizing: border-box;
  overflow: auto;
  width: 100%;
  height: 100%; }
  @media screen and (-ms-high-contrast: active) {
    md-dialog-container {
      outline: solid 1px; } }

/*# sourceMappingURL=dialog-container.css.map */


is this .css file's problem???

**Comment by crisbeto** [comment]
The positioning styles that I pasted should be in the overlay styles. They should be at `core/overlay/overlay.css`.

**Comment by Striveyazi** [comment]
oh. I read the path, but did not find.I put this directory screenshots for you。
![image](https://cloud.githubusercontent.com/assets/18276182/21218464/b32b51f2-c2eb-11e6-87c2-6a2c9d8cd69a.png)

**Comment by crisbeto** [comment]
My bad, looks like the overlay styles are in the generated theme files. Do you use the theming? You can see how to set it up in our guide: https://github.com/angular/material2/blob/master/docs/theming.md. You only need to include one of the pre-built themes.

**Comment by Striveyazi** [comment]
its my error.i didnt use this reference theme file.i will try it again.thank u very much.

**Comment by Striveyazi** [comment]
this problem is solved, thank u very much for your patience

**Comment by Cleudi** [comment]
I basically have the same problem (beta version). Will styles be moved to the component itself or will it be mandatory to use theming as described before?

**Comment by crisbeto** [comment]
Some of these styles don't have a corresponding component @Cleudi, hence why they are added to the theme. Also even if we did move the structural styles away from the theme, your app probably wouldn't look good either since all of the color-related styles are there.
