### ISSUE TITLE
input placeholder covers value when using OnPush detection strategy

### ISSUE THREAD

**Issue by fxck** [angular/material2#3005]
I know there were couple of these before, but it seems to be happening again https://gist.run/?id=d815c9d4e98685976793d074fcc89c23 

cc @kara @mmalerba maybe?

**Comment by johnqiuwan** [comment]
I had the exactly same issue on my project that the placeholder value overlap with the input value.

**Comment by realappie** [comment]
I have the same issue when using reactive forms `yForm.controls['xControl'].setValue('foobar')`

![issue gif](https://i.gyazo.com/ebf9227ba14684a665d111d692165620.gif)

If I dont change the input using the keyboard, the input just puts the placeholder back to its original position as if the input is empty which its not.

**Comment by mmalerba** [comment]
There are some similar issues to this one that have already been fixed (#2816, #2837). This one only applies if you are using `ChangeDetectionStrategy.OnPush`

**Comment by ggranum** [comment]
I'm seeing this manifest in browser-populated fields - specifically userName and password fields populated by Chrome et. al. My normal temporary hack of 

`
setTimeout(() => {
      this.changeDetectorRef.markForCheck()
    }, 100)
`

fails for this case, however.

**Comment by JacobBrandt** [comment]
I'm also seeing this behavior not only for input but on select as well when using OnPush.  The select control doesn't have it's value selected until a form control is given focus.  Similar to what @realappie shows.

![onpushbug](https://cloud.githubusercontent.com/assets/5314322/24074646/7ef22214-0bd2-11e7-8915-98acce9e5526.gif)

**Comment by mjolk** [comment]
maybe related to #2663 says it's fixed but i'm still having this issue using select in combination with reactive forms/OnPush change detection.( Angular 4.0.0, material 2.0.0.beta2)

**Comment by mjolk** [comment]
for me this all works as expected now.(beta 3)  Good work!

**Comment by eyalewin** [comment]
@mjolk , can you share how did was it fixed for you? i still can't have it working. 
take a look at this: [https://plnkr.co/edit/FncXapgEEdqJU7R3kU8X?p=preview](url)

**Comment by FilipeQ** [comment]
@mjolk What you do for OnPush work with input placeholder, i have last version (2.0.0-beta.3) and the problem persist.

**Comment by ggranum** [comment]
Still an issue for me as well. I've worked around it with:

```
setTimeout(() => {
      changeDetectorRef.markForCheck()
    }, 100)
```
In ngOnInit / ngAfterViewInit.

**Comment by eyalewin** [comment]
@ggranum worked out for me, just that I've put it in the subscribe where the actual data is rendered.
but still, I would have expected that this issue has been solved.

**Comment by mjolk** [comment]
i use markForCheck() as well, not specifically for this reason , but it apparently was the reason it worked( before in the exact same setup it didn't). It is logical( to me in my use case) the render does not happen without marking the component dirty( in a situation where there is new data from a subscription) manually so i did not think it was a bug/it was fixed

**Comment by radoslavpetranov** [comment]
I came to report the same issue - glad I searched before creating a new one. Here's my plunker for good measure

https://plnkr.co/edit/laqgCj3vQI8PPbnXc4en?p=preview

**Comment by YeomansIII** [comment]
Still seeing this issue: https://github.com/angular/material2/issues/4814

**Comment by taokakao** [comment]
I am still facing issue even with timeout hack. Is there anything else can be done to fix?

**Comment by MaickelHubner** [comment]
This problem back in beta.10.
Can anybody solve it?

**Comment by willshowell** [comment]
@MaickelHubner can you reproduce it and open a new issue?

**Comment by jososaga** [comment]
This problem is back in beta 12, any solution?

**Comment by MaxTheMax2007** [comment]
Would be great to have a solution because as it is now its not possible to use fields(( ... It was working fine in beta 11 ..
