### ISSUE TITLE
docs(md-icon): api missing text

### ISSUE THREAD

**Issue by julianobrasil** [angular/material2#5793]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behavior?

See the complete explanation of an api item

#### What is the current behavior?

Some text is missing in specific parts of the [**md-icon** docs (API Tab)](https://material.angular.io/components/icon/api). Where it should be written something like:

_"Returns an Observable that produces the icon (as an `<svg>` DOM element) from the given URL. The response from the URL may be cached so this will not always cause an HTTP request, but the produced element will always be a new copy of the originally fetched icon. (That is, it will not contain any modifications made to elements previously returned)."_

you actually see what is shown in the image bello (that's because of the `<svg>` tag in the code comment):

![image](https://user-images.githubusercontent.com/25405143/28243123-b1b22fc0-6995-11e7-83f0-673d59d0d130.png)

**Comment by donroyco** [comment]
Here's the URL for reference: https://material.angular.io/components/icon/api

**Comment by julianobrasil** [comment]
@willshowell, what's the right path to avoid this error in docs? Does it follow the same Github markdown rules? I mean, is it just a matter of use the backticks (\``<sgv>`\` instead of `<sgv>`)?

**Comment by donroyco** [comment]
@julianobrasil *svg ;)

**Comment by julianobrasil** [comment]
Thanks, @donroyco! Not home right now, but I'll fix it and submit a PR later if no one do it (I was just showing the Material 2 Project to a reluctant developer and this error in the docs didn't help my point of view 😸 ).

**Comment by willshowell** [comment]
@julianobrasil Yeah it'd almost certainly be fixed by backticks. I'm sure no one would mind either if you added a lint rule to enforce HTML tag escaping too (see the `noExposedTodoRule`) 😁

**Comment by julianobrasil** [comment]
@willshowell, of course... just need to make sure that the backticks escapes HTML tags. @donroyco wrote something about asterisks above.

**Comment by donroyco** [comment]
@julianobrasil It was just a typo reference: `sgv` » `svg`

**Comment by julianobrasil** [comment]
@donroyco, that's why my wife keeps saying I need some rest once in a while 😃. I haven't corrected the docs yet because yesterday I got involved with a mysterious behavior in a project (at the end I found out  that if you create an @Output named "change", or named after any html native event, Angular will bubble the native event through it).  But I did submit the PR with the tslint rule at least.

**Comment by futurizing** [comment]
This issue still persists as of today.
Why the PR #5824 still hasn't been merged? I think it's a valid fix.

**Comment by julianobrasil** [comment]
Another one was merged today with the same fix: #7756

**Comment by futurizing** [comment]
Nice! :) So this issue can be closed then?

**Comment by julianobrasil** [comment]
Right now!
