### ISSUE TITLE
Dialog with fixed height less than 100% has 2 scrollbars

### ISSUE THREAD

**Issue by tytskyi** [angular/material2#6584]
#### What is the expected behavior?
Dialog with fixed height, that is less than 100% to have only one scroll bar - for content section.

#### What is the current behavior?
Dialog has 2 scrollbars - 1 for content and 1 for the whole dialog.

#### What are the steps to reproduce?
https://plnkr.co/edit/1teyLZLR7MVsrZLPD94V?p=preview

#### What is the use-case or motivation for changing an existing behavior?
2 scrollbars is weak user-experience.

#### Which versions of Angular, Material, OS, TypeScript, browsers are affected?
Browsers: Chrome, IE11
Material: 2.0.0-beta.6, 2.0.0-beta.8
OS, Typescript - not applicable

#### Is there anything else we should know?
Probably the same is applicable to fixed width, but lets not noise the issue with it.

**Comment by julianobrasil** [comment]
It seems ok over here (Chrome, Windows 10);

![image](https://user-images.githubusercontent.com/25405143/29590211-1c887ee8-876f-11e7-90f5-6fe7bc1d6695.png)

**Comment by tytskyi** [comment]
@julianobrasil could you shrink browser vertically?

![image](https://user-images.githubusercontent.com/2727037/29590453-2fd714b6-879a-11e7-9f2b-42da294eb4c2.png)

I have this problem on 2 laptops + 1 desktop monitor

- Laptop 1, 13" full hd
- Laptop 2, 13" 4k
- Desktop monitor 24" regular resolution

**Comment by julianobrasil** [comment]
It happened with the browser shrinked.

**Comment by surachaitanya** [comment]
Is there any temporary solution I can apply, until this is fixed?

**Comment by mergin** [comment]
The issue is still happening with fixed height:
```
const dialogRef = this.dialog.open(DialogOverviewExampleDialog, {
      height: '400px',
      width: '250px',
      data: {name: this.name, animal: this.animal}
    });
```

 https://stackblitz.com/edit/angular-axeibr

**Comment by mycroft16** [comment]
Came here for a solution and it's happening to me as well with a fixed height dialog. Same as the previous post. It only happens for me if I use the mat-dialog-content directive to wrap my content. Otherwise the main dialog scrollbar is the only one present.

Use cases:
fixed height on dialog
use mat-dialog-content directive
double scroll bars
------------
fixed height on dialog
no mat-dialog-content
single scroll bar, but not fixed header
------------
no fixed height on dialog
use mat-dialog-content-directive
single scroll bar, but not the height I want.

**Comment by tommueller** [comment]
Almost another year has passed by and this error still persists. No news whatsoever on this?

**Comment by Laurensvdw** [comment]
@andrewseguin @crisbeto Could you please look into this again. As @mycroft16 stated the problem is not there when you don't use the mat-dialog-content slot... But when you do that and you have focus on the action buttons on init of dialog, you do not see the dialog title. And for the content only the bottom part... 
![image](https://user-images.githubusercontent.com/25631940/110930448-68cb8c00-8329-11eb-8762-66552efa183d.png)

So if you use the dialog as it is supposed to be, to have "sticky" header title and footer actions, you get this:
![image](https://user-images.githubusercontent.com/25631940/110930897-f1e2c300-8329-11eb-8e13-21bba08576cd.png)

[Test stackblitz](https://stackblitz.com/edit/angular-l1saub?file=src%2Fapp%2Fdialog-content-example.ts)

The expected result would be:
![image](https://user-images.githubusercontent.com/25631940/110932886-57d04a00-832c-11eb-8b0c-55d0a8b30591.png)

Therefore you need to look at the dialog config if there is a value present "height" or "maxHeight" and according to those values, calculations need to be made to set the correct "height" or "maxHeight" on the mat-dialog-content as inline styling (same as for the panel)... In our example this would be "max-height: 256px". We need to do this because the mat-dialog-content class has a fixed "responsive" height, being "max-height: 65vh;".

Thanks for looking into it and please do keep us posted!

**Comment by brandart** [comment]
this is very annoying. is there any way around?

**Comment by RueDeRennes** [comment]
is there now a fix?

**Comment by nikhil-clearcals** [comment]
Is this bug fixed by any chance ?

**Comment by uncleGera** [comment]
I have a workaround. I was able to solve the issue by adding this styles to `.mat-dialog-container` and dialog component:
```
.mat-dialog-container {
  overflow: unset;
  display: flex;
  flex-direction: column;

  dialog-content-example-dialog {
    display: flex;
    flex-direction: column;
    min-height: 1px;
  }
}
```
This is how it looks like:
![image](https://user-images.githubusercontent.com/27092603/166766344-0cb935eb-f426-4d69-a636-43a527f39586.png)
[Stackblitz example](https://stackblitz.com/edit/angular-l1saub-j6rspo?file=src/app/dialog-content-example-dialog.scss)

**Comment by masum7** [comment]
It's a big problem particularly iOS devices as the actions buttons zoom out with full screen modal but if you set maxHeight it brings scrollbar for android devices.
